version: '3'
services:
  api:
    image: thiagorente/apiaula
    # build: .
    ports:
      - "80:80"
    links:
      - mysql
    depends_on:
      - mysql
    restart: unless-stopped 

  mysql:
    image: mysql
    container_name: mysql
    ports: 
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    command: --default-authentication-plugin=mysql_native_password
